### ISSUE TITLE
Inquiry regarding the availability of a pre-trained model

### ISSUE THREAD

**Issue by TLB-MISS** [Wi-sc/GenMesh#2]
Thank you for your good work.

Are there any plans to provide a pre-trained model?

Thanks.

**Comment by Wi-sc** [comment]
Hi there, thanks for your interest in our work. The object-centered model is here: https://drive.google.com/file/d/1uKWj8wmAdX4E6tWBHP2fTZZiwnPMevX6/view?usp=drive_link. 

If you have any other issues, feel free to ask me here.

**Comment by TLB-MISS** [comment]
thank you!
I have sent an access request.

**Comment by Wi-sc** [comment]
The link should be public now.

**Comment by TLB-MISS** [comment]
Thanks!!
